// Enumerate
enum pilihanUtama{
    OPERASI_MATEMATIKA_DASAR = 1, TRIGONOMETRI, LOGARITMA, STATISTIKA, TEORI_BILANGAN, BARISAN_DAN_DERET
};
enum Operasi_Matdas {
    PERKALIAN = 1, PEMBAGIAN, PENJUMLAHAN, PENGURANGAN, AKAR_KUADRAT, AKAR_KUBIK, EPOWX, EKSPONENSIAL, FAKTORIAL, PERMUTASI, KOMBINASI
};
enum Trigonometri{
    TRIGONSIN = 1, TRIGONCOS, TRIGONTAN, TRIGONCSC, TRIGONSEC, TRIGONCOT, TRIGONASIN, TRIGONACOS, TRIGONATAN 
};
enum Logaritma{
    LOG10 = 1, LEN, LOGBASISLAIN
};
enum statistik{
    MEAN = 1, MEDIAN, MODUS, STDEVPOP, STDEVSAM, DESIL, PERSENTIL, DEVIASIRATARATA, DATAMINMAXRANGE, REGRESIKORELASI
};
enum teori_bilangan {
    APAKAHPRIMA = 1, MENDATAPRIMA, MODEXP, MODFAKTORIAL, FAKTORPRIMA
};
enum barisan_dan_deret {
    BARISANDERETARITMATIKA = 1, BARISANDERETGEOMETRI, BARISANFIBONACCI
};

// Struct
struct data{
    int int1, int2, int3;
    double hasil, db1, db2, db3;
}; 

struct pilihanUser{
    char pilihan[200];
};